
USE mykey;

INSERT INTO posts(thread_id, text, poster, timestamp) VALUES (1, 'i hope this post works', 'david', date('now'));
INSERT INTO posts(thread_id, text, poster, timestamp) VALUES (1, 'lets give it another try', 'david', date('now'));
INSERT INTO posts(thread_id, text, poster, timestamp) VALUES (1, 'i know what you mean it should work', 'yashdeep', date('now'));
INSERT INTO posts(thread_id, text, poster, timestamp) VALUES (1, 'i am not sure though', 'yashdeep', date('now'));
