
USE mykey;

INSERT INTO posts(id, thread_id, text, poster, timestamp) VALUES (1, 1, 'i hope this post works', 'david', date('now'));
INSERT INTO posts(id, thread_id, text, poster, timestamp) VALUES (2, 1, 'lets give it another try', 'david', date('now'));
INSERT INTO posts(id, thread_id, text, poster, timestamp) VALUES (3, 1, 'i know what you mean it should work', 'yashdeep', date('now'));
INSERT INTO posts(id, thread_id, text, poster, timestamp) VALUES (4, 1, 'i am not sure though', 'yashdeep', date('now'));
